//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diploma.res
{
    using System;
    using System.Collections.Generic;
    
    public partial class credentials
    {
        public int cred_id { get; set; }
        public string cred_user { get; set; }
        public string cred_pass { get; set; }
        public Nullable<int> access_id { get; set; }
    
        public virtual access access { get; set; }
    }
}
