//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRKTK030225.res
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credentials
    {
        public int LOG_ID { get; set; }
        public string LOGIN { get; set; }
        public string PASSWD { get; set; }
        public int AccessLevel_ID { get; set; }
    
        public virtual AccessLevels AccessLevels { get; set; }
    }
}
