//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRKTK030225.res
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hardware
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hardware()
        {
            this.Movement = new HashSet<Movement>();
        }
    
        public int HARD_ID { get; set; }
        public string HARD_NAME { get; set; }
        public string HARD_STATUS { get; set; }
        public int HARDTYPE_ID { get; set; }
        public int Personnel_ID { get; set; }
        public int Supplier_ID { get; set; }
        public Nullable<int> Movement_ID { get; set; }
        public Nullable<int> Repair_ID { get; set; }
        public int HARD_QUANTITY { get; set; }
    
        public virtual HardwareType HardwareType { get; set; }
        public virtual Personnel Personnel { get; set; }
        public virtual Repair Repair { get; set; }
        public virtual Suppliers Suppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movement> Movement { get; set; }
    }
}
