//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diploma.res
{
    using System;
    using System.Collections.Generic;
    
    public partial class hardtype
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hardtype()
        {
            this.hardware = new HashSet<hardware>();
        }

        public static List<String> TableNames
        {
            get
            {
                List<String> tableNames = new List<String>()
                {
                    "ИД",
                    "Наименование типа"
                };

                return tableNames;
            }
        }

        public int hardtype_id { get; set; }
        public string hardtype_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hardware> hardware { get; set; }
    }
}
