//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diploma.res
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<department> department { get; set; }
        public virtual DbSet<hardtype> hardtype { get; set; }
        public virtual DbSet<hardware> hardware { get; set; }
        public virtual DbSet<movement> movement { get; set; }
        public virtual DbSet<personnel> personnel { get; set; }
        public virtual DbSet<repair> repair { get; set; }
        public virtual DbSet<supplier> supplier { get; set; }
        public virtual DbSet<supply> supply { get; set; }
        public virtual DbSet<writeoff> writeoff { get; set; }
        public virtual DbSet<access> access { get; set; }
        public virtual DbSet<credentials> credentials { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
