//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diploma.res
{
    using System;
    using System.Collections.Generic;
    
    public partial class movement
    {
        public int movement_id { get; set; }
        public Nullable<System.DateTime> movement_date { get; set; }
        public string movement_from { get; set; }
        public string movement_to { get; set; }
        public Nullable<int> personnel_id { get; set; }
        public Nullable<int> hard_id { get; set; }
    
        public virtual hardware hardware { get; set; }
        public virtual personnel personnel { get; set; }
    }
}
