//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRKTK030225.res
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movement
    {
        public int Movement_ID { get; set; }
        public int HARD_ID { get; set; }
        public string Movement_From { get; set; }
        public string Movement_To { get; set; }
        public Nullable<System.DateTime> Movement_Date { get; set; }
    
        public virtual Hardware Hardware { get; set; }
    }
}
