//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diploma.res
{
    using System;
    using System.Collections.Generic;
    
    public partial class personnel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public personnel()
        {
            this.hardware = new HashSet<hardware>();
            this.movement = new HashSet<movement>();
        }
    
        public string fullname { 
            get
            {
                return this.personnel_lastname + " " + this.personnel_name + " " + personnel_patronymic;
            } 
        }

        public static List<String> TableNames
        {
            get
            {
                List<String> tableNames = new List<String>()
                {
                    "ИД",
                    "Фамилия",
                    "Имя",
                    "Отчество",
                    "Номер телефона",
                    "Адрес проживания",
                    "Отдел",
                    "Должность"
                };

                return tableNames;
            }
        }

        public int personnel_id { get; set; }
        public string personnel_lastname { get; set; }
        public string personnel_name { get; set; }
        public string personnel_patronymic { get; set; }
        public string personnel_phone { get; set; }
        public string personnel_address { get; set; }
        public Nullable<int> department_id { get; set; }
        public string personnel_title { get; set; }
    
        public virtual department department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hardware> hardware { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<movement> movement { get; set; }
    }
}
