//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRKTK030225.res
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personnel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personnel()
        {
            this.Hardware = new HashSet<Hardware>();
        }
    
        public int Personnel_ID { get; set; }
        public string Personnel_Name { get; set; }
        public string Personnel_MiddleName { get; set; }
        public string Personnel_LastName { get; set; }
        public string Personnel_PhoneNumber { get; set; }
        public string Personnel_Address { get; set; }
        public string Personnel_Title { get; set; }
        public string Personnel_Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hardware> Hardware { get; set; }
    }
}
