//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diploma.res
{
    using System;
    using System.Collections.Generic;
    
    public partial class supply
    {
        public int supply_id { get; set; }
        public Nullable<System.DateTime> supply_date { get; set; }
        public Nullable<int> supplier_id { get; set; }
        public Nullable<int> hard_id { get; set; }
    
        public virtual hardware hardware { get; set; }
        public virtual supplier supplier { get; set; }
    }
}
