//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diploma.res
{
    using System;
    using System.Collections.Generic;
    
    public partial class writeoff
    {
        public static List<String> TableNames
        {
            get
            {
                List<String> tableNames = new List<String>()
                {
                    "ИД",
                    "Дата списания",
                    "Причина списания",
                    "Оборудование"
                };

                return tableNames;
            }
        }
        public int writeoff_id { get; set; }
        public Nullable<System.DateTime> writeoff_date { get; set; }
        public string writeoff_reason { get; set; }
        public Nullable<int> hard_id { get; set; }
    
        public virtual hardware hardware { get; set; }
    }
}
